version: "3.7"
services:
    app:
        build:
            args:
                user: Shawon
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: project-management
        container_name: project-management-application
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - database
        links:
            - database
        networks:
            - project-management-network
    nginx:
        image: nginx:alpine
        container_name: project-management-nginx
        restart: unless-stopped
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ./:/var/www
            - ./.docker/nginx:/etc/nginx/conf.d/
        networks:
            - project-management-network
        depends_on:
            - database
            - phpmyadmin
    database:
        image: mysql:5.7
        container_name: project-management-database
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - project-management-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: project-management-phpmyadmin
        restart: unless-stopped
        tty: true
        depends_on:
            - database
        ports:
            - ${PMA_PORT}:80
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - project-management-network

networks:
    project-management-network:
        driver: bridge
